apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: icy-lion-dotnet-basic
  janus-idp.io/tekton: icy-lion-dotnet-basic
  backstage.io/kubernetes-id: icy-lion-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: icy-lion-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
